version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    command: ["python", "bot/__main__.py"]

  # db:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=secret
  #     - POSTGRES_DB=vpn_bot_db
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

#  app:  # Go-backend, закомментирован до готовности
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - DB_HOST=db
#      - DB_USER=postgres
#      - DB_PASSWORD=secret
#      - DB_NAME=vpn_bot_db
#      - DB_PORT=5432

volumes:
  pgdata:
